### ISSUE TITLE
[BUG] Opening a bundle filters all non installed packages once, but shows after any refresh

### ISSUE THREAD

**Issue by only-su** [marticliment/UniGetUI#2635]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 22631.3958

### Describe your issue

As long as it seems to me if the package is not installed it does not show by default when opening a bundle .json file. When opening you will be met with a blank screen and the view subtitle will say `X packages were found, 0 of which match the specified filters` where X is the number of packages on the bundle.json.

I don't think this is expected. But the failure doesn't seem constant, sometimes it opens normally. Sometimes some packages show and others don't. I can test further if given new approaches.

### Steps to reproduce the issue

Open a bundle with uninstalled package. See that no package is shown.

Try clear source selection and select all again, package shows.

Loading the bundle.json once again also make the packages appear.

I think, by reading the logs, that it seems related to the order of operations, maybe as it creates the options after when the package does not exist locally, it can't render when it loads and only after a refresh or reload it shows.

### UniGetUI Log

```text
[14/08/2024 13:42:45] Adding native package with id=Google.Chrome to bundle as a VALID package...
[14/08/2024 13:42:45] Creating new instance of InstallationOptions for package UniGetUI.PackageEngine.PackageClasses.ImportedPackage, as no instance was found in cache
```

### Package Managers Logs

```text
Not related
```

### Screenshots and videos

clearing and selecting sources renders the package:
https://github.com/user-attachments/assets/566941d9-fc38-46a7-874c-93dccf870b27

**Comment by marticliment** [comment]
I will investigate

**Comment by only-su** [comment]
Is this fix on beta? I was testing the other issue and it is still happening :(

https://github.com/user-attachments/assets/4839f62a-046b-4fdb-a133-fafc9b78ab69

**Comment by marticliment** [comment]
Yes, this issue should have been fixed, and, at least to what I could reproduced it got fixed

**Comment by only-su** [comment]
It's also happening in a place I (at least that I remember) didn't notice before, in the "Discover Packages" when searching.
Sometimes I need to search twice (and now clearing and selecting again do not always work) as the same issue that was happening with bundles occur, I search and the page subtitle becomes "X packages were found, 0 of which match the specific filters" and no package is shown

**Comment by marticliment** [comment]
On the discover packages page you may need to change the "Search Mode" to "Show similar packages"

**Comment by marticliment** [comment]
If the issue is happening only on the Discover PAckages page then it was fixed

**Comment by only-su** [comment]
No no, I send a video with it happening on bundles here

> It's also happening in a place I (at least that I remember) didn't notice before, in the "Discover Packages" when searching. Sometimes I need to search twice (and now clearing and selecting again do not always work) as the same issue that was happening with bundles occur, I search and the page subtitle becomes "X packages were found, 0 of which match the specific filters" and no package is shown

At least when selecting to add a package to a bundle It still happens

**Comment by marticliment** [comment]
Does it happen always? I am not able to reproduce the issue

**Comment by only-su** [comment]
I tested and could record it not happening and happening. So I think It's not always. But it seems to be more consistent when you first open unigetui.

(I sped up because of the file size cap)
https://github.com/user-attachments/assets/99f5f7ec-2cb1-4a63-91b8-c5cadf3e095b

**Comment by ninbura** [comment]
The problem isn't exclusive to non-installed packages, nor is it exclusive to the bundles tab. Frequently applications will not list on any tab of the application, and you have to check and uncheck winget to make them show.

I've been able to replicate this on 8 systems across 5 different chipsets.

https://github.com/user-attachments/assets/1d642b89-8727-441d-a5cd-60b7cbbbd7b7

**Comment by ninbura** [comment]
Apologies, I missed the context that it was working in the latest beta version. It appears to be fixed on my end when running `v3.1.2-beta0`.

**Comment by marticliment** [comment]
This PR should have fixed the issues: https://github.com/marticliment/UniGetUI/pull/3597
(I forgot to mention this)
