### ISSUE TITLE
[BUG] The packages list is empty sometimes when searching for something a second time

### ISSUE THREAD

**Issue by amethyze** [marticliment/UniGetUI#2841]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 23H2 22631.4249

### Describe your issue

If I search for a package, the list shows up normally. If I try searching for a different package, the list seems to be empty.

### UniGetUI Log

```text
[16/10/2024 02:26:37]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[16/10/2024 02:26:37]
[16/10/2024 02:26:37] Version Code:  3.11
[16/10/2024 02:26:37] Encoding Code Page set to 850
[16/10/2024 02:26:37] Using bundled GSudo at C:\Users\Kody\AppData\Local\Programs\UniGetUI\Assets\Utilities\gsudo.exe
[16/10/2024 02:26:37] Loaded language locale: en
[16/10/2024 02:26:38] Randomly-generated background API auth token for the current session: jpp2nowwvb9u9m8duwjmbof1wssltc382vs3wdxsx2hg7pkqkd2jryjuwp4jqbjm
[16/10/2024 02:26:38] Api running on http://localhost:7058
[16/10/2024 02:26:38] Lang files were updated successfully from GitHub
[16/10/2024 02:26:38] UniGetUI is up to date
[16/10/2024 02:26:38] Downloaded new icons and screenshots successfully!
[16/10/2024 02:26:41] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.2 from C:\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:42] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   6.0.427
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.8.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Kody\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:45] Command scoop was not found on the system
[16/10/2024 02:26:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\Kody\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   This is try 1/3. Retrying after 400 milliseconds.
                      █    Error converted to warning:
                      █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.13744.update' is denied.
                      █   This is try 2/3. Retrying after 600 milliseconds.
                      █    Error converted to warning:
                      █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.13744.update' is denied.
                      █   Maximum tries of 3 reached. Throwing error.
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.3
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4249                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4249                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[16/10/2024 02:26:51] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[16/10/2024 02:26:51] Dependency WinGet PowerShell Module for manager Winget is present
[16/10/2024 02:27:03] Dependency .NET Tools Outdated for manager .NET Tool is present
[16/10/2024 02:27:03] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[16/10/2024 02:27:09] Found 145 installed packages from Winget
[16/10/2024 02:27:09] Command parse_pip_search.exe was not found on the system
[16/10/2024 02:27:10] Found 0 available updates from .NET Tool
[16/10/2024 02:27:12] Found 83 installed packages from Pip
[16/10/2024 02:27:12] Found 0 available updates from Chocolatey
[16/10/2024 02:27:12] Found 0 installed packages from Chocolatey
[16/10/2024 02:27:12] Found 0 installed packages from PowerShell
[16/10/2024 02:27:15] Found 0 available updates from PowerShell
[16/10/2024 02:27:15] Found 2 installed packages from .NET Tool
[16/10/2024 02:27:15] Found 2 installed packages from PowerShell7
[16/10/2024 02:27:15] Found 19 available packages from Npm with the query roblox
[16/10/2024 02:27:15] Found 3 available packages from Winget with the query roblox
[16/10/2024 02:27:16] Error finding packages on manager Pip with query roblox
[16/10/2024 02:27:17] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Users\Kody\AppData\Local\Programs\UniGetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 97
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 163
[16/10/2024 02:27:17] Found 13 available packages from .NET Tool with the query roblox
[16/10/2024 02:27:17] Found 3 available packages from Chocolatey with the query roblox
[16/10/2024 02:27:17] Found 0 available updates from Npm
[16/10/2024 02:27:17] Found 0 installed packages from Npm
[16/10/2024 02:27:19] Found 5 available updates from Winget
[16/10/2024 02:27:21] Found 0 available updates from PowerShell7
[16/10/2024 02:27:24] Found 0 available updates from Pip
[16/10/2024 02:27:29] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:27:29] Icon for package Roblox.Roblox was not found, returning default icon
[16/10/2024 02:27:34] Found 2 installed packages from .NET Tool
[16/10/2024 02:27:34] Found 83 installed packages from Pip
[16/10/2024 02:27:36] Found 0 installed packages from Chocolatey
[16/10/2024 02:27:37] Found 145 installed packages from Winget
[16/10/2024 02:27:39] Found 0 installed packages from PowerShell
[16/10/2024 02:27:40] Found 2 installed packages from PowerShell7
[16/10/2024 02:27:40] Found 0 installed packages from Npm
[16/10/2024 02:27:47] Found 0 available packages from PowerShell with the query roblox
[16/10/2024 02:27:47] Found 0 available packages from PowerShell7 with the query roblox
[16/10/2024 02:27:51] Command parse_pip_search.exe was not found on the system
[16/10/2024 02:27:51] Found 13 available packages from .NET Tool with the query roblox
[16/10/2024 02:27:51] Found 3 available packages from Winget with the query roblox
[16/10/2024 02:27:55] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:27:55] Icon for package Roblox.Roblox was not found, returning default icon
[16/10/2024 02:27:55] Found 19 available packages from Npm with the query roblox
[16/10/2024 02:27:55] Found 3 available packages from Chocolatey with the query roblox
[16/10/2024 02:27:57] Error finding packages on manager Pip with query roblox
[16/10/2024 02:27:57] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Users\Kody\AppData\Local\Programs\UniGetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 97
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 163
[16/10/2024 02:28:28] Found 0 available packages from PowerShell7 with the query roblox
[16/10/2024 02:28:30] Found 0 available packages from PowerShell with the query roblox
[16/10/2024 02:28:46] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:28:46] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Discord.Discord
[16/10/2024 02:28:46] Icon for package Discord.Discord stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\Discord.Discord.png
[16/10/2024 02:28:46] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:28:46] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.PowerShell
[16/10/2024 02:28:46] Icon for package Microsoft.PowerShell stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.PowerShell.png
[16/10/2024 02:28:46] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:28:46] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=RustDesk.RustDesk
[16/10/2024 02:28:46] Icon for package RustDesk.RustDesk stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\RustDesk.RustDesk.png
[16/10/2024 02:28:46] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:28:46] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.WindowsTerminal
[16/10/2024 02:28:46] Icon for package Microsoft.WindowsTerminal stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.WindowsTerminal.png
[16/10/2024 02:29:09] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:29:09] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=RustDesk.RustDesk
[16/10/2024 02:29:09] Icon for package RustDesk.RustDesk stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\RustDesk.RustDesk.png
[16/10/2024 02:29:09] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:29:09] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=RustDesk.RustDesk
[16/10/2024 02:29:09] Icon for package RustDesk.RustDesk stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\RustDesk.RustDesk.png
[16/10/2024 02:30:41] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:30:41] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=RustDesk.RustDesk
[16/10/2024 02:30:41] Icon for package RustDesk.RustDesk stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\RustDesk.RustDesk.png
[16/10/2024 02:30:41] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:30:41] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=RustDesk.RustDesk
[16/10/2024 02:30:41] Icon for package RustDesk.RustDesk stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\RustDesk.RustDesk.png
[16/10/2024 02:31:20] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:31:20] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=RustDesk.RustDesk
[16/10/2024 02:31:20] Icon for package RustDesk.RustDesk stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\RustDesk.RustDesk.png
[16/10/2024 02:31:26] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:31:26] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.PowerShell
[16/10/2024 02:31:26] Icon for package Microsoft.PowerShell stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.PowerShell.png
[16/10/2024 02:31:26] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[16/10/2024 02:31:26] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.PowerShell
[16/10/2024 02:31:26] Icon for package Microsoft.PowerShell stored on C:\Users\Kody\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.PowerShell.png
[16/10/2024 02:32:02] Found 0 available updates from .NET Tool
[16/10/2024 02:32:03] Found 0 available updates from Chocolatey
[16/10/2024 02:32:07] Found 0 available updates from PowerShell
[16/10/2024 02:32:08] Found 5 available updates from Winget
[16/10/2024 02:32:09] Found 0 available updates from Npm
[16/10/2024 02:32:18] Found 0 available updates from PowerShell7
[16/10/2024 02:32:20] Found 0 available updates from Pip
[16/10/2024 02:32:32] Found 0 available updates from .NET Tool
[16/10/2024 02:32:34] Found 0 available updates from Chocolatey
[16/10/2024 02:32:35] Found 5 available updates from Winget
[16/10/2024 02:32:37] Found 0 available updates from PowerShell
[16/10/2024 02:32:38] Found 0 available updates from Npm
[16/10/2024 02:32:45] Found 0 available updates from PowerShell7
[16/10/2024 02:32:48] Found 0 available updates from Pip
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 16/10/2024 02:26:45
Process end time:   16/10/2024 02:26:45

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Kody\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 16/10/2024 02:26:50
Process end time:   16/10/2024 02:27:03

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 16/10/2024 02:26:50
Process end time:   16/10/2024 02:27:09

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 16/10/2024 02:26:51
Process end time:   16/10/2024 02:26:57

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 16/10/2024 02:27:03
Process end time:   16/10/2024 02:27:15

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 16/10/2024 02:27:10
Process end time:   16/10/2024 02:27:19

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 16/10/2024 02:27:30
Process end time:   16/10/2024 02:27:37

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 16/10/2024 02:27:51
Process end time:   16/10/2024 02:27:51

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Kody\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 16/10/2024 02:31:59
Process end time:   16/10/2024 02:32:00

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 16/10/2024 02:32:00
Process end time:   16/10/2024 02:32:08

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Kody\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 16/10/2024 02:32:29
Process end time:   16/10/2024 02:32:30

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 16/10/2024 02:32:30
Process end time:   16/10/2024 02:32:35

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Please test the latest beta, as similar issues have been fixed here: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta3

**Comment by amethyze** [comment]
The error is still present, this still isn't working properly.

**Comment by marticliment** [comment]
Can you please share a screen recording of the issue in 3.1.2 stable?
