### ISSUE TITLE
[BUG] DDE Server Window: UniGetUI.exe - System Error (overrun of a stack-based buffer)

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#3094]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

Manually quitting UnitGetUI. Doesn't always occur. Perhaps only after a system sleep / hibernation with UniGetUI still running in the background.

### Steps to reproduce the issue

1. More menu.
2. Quit UniGetUI.

### UniGetUI Log

```text
\-
```

### Package Managers Logs

```text
\-
```

### Relevant information

Also noticed this occurring during the last beta.

```
---------------------------
DDE Server Window: UniGetUI.exe - System Error
---------------------------
The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.
---------------------------
OK
---------------------------
```

### Screenshots and videos

Forgot to take a screenshot, but the above is a copy of the popup window which appeared after pressing quit.

**Comment by marticliment** [comment]
Is this some kind of third-party post-mortem debugger, or this is a windows popup?

**Comment by Xites** [comment]
> Is this some kind of third-party post-mortem debugger, or this is a windows popup?

I've the same problem. It's a Windows pop-up. 
Windows log (Dutch): 
Toepassingspop-up: UniGetUI Elevator.exe - Systeemfout : Er is een bufferoverschrijdingsfout opgetreden voor stack-buffer in deze toepassing. Via deze overschrijdingsfout kan een kwaadwillige gebruiker de controle over deze toepassing verkrijgen. 
![image](https://github.com/user-attachments/assets/8dead614-f680-4059-afef-eb83b55aa3bc)

**Comment by Xites** [comment]
> i suppose it only happens on latest 3.1.4, didn't happened on latest beta and before

I'm not sure but I think so. It was this week after an automatic update.

**Comment by Xites** [comment]
Update 3.1.5 solved this issue for me. Thanks

**Comment by ryanull24** [comment]
Still present for me in 3.1.5

**Comment by marticliment** [comment]
It appears that this issue is not actually a _bug_, but an odd windows behaviour: https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655

Nevertheless I will still investigate its cause and attempt to fix it

**Comment by marticliment** [comment]
This issue should be fixed by #3238, which, among other changes, allows for proper process termination instead of killing the process when using any of the exit mechanisms.

**Comment by wearysky** [comment]
FYI - still getting this error, showed up twice today. Acrobat Reader and Firefox were sitting in my "to be updated" list but wouldn't update after the error, even after quitting and reopening the app. After a reboot they were gone.
