### ISSUE TITLE
[BUG] Cannot install applications that require admin permissions, outside UnigetUI works

### ISSUE THREAD

**Issue by eizedev** [marticliment/UniGetUI#3274]
### Please confirm these before moving forward

- [x] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [x] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [x] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [x] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.6

### Windows version, edition, and architecture

Windows 10 22H2 (19045.5371)

### Describe your issue

Hi,
first, thanks for this great product!! 
I've had this problem with UniGet for quite a while (on several PCs) and thought with the latest fix in 3.1.6 ("A long-standing issue where WinGet would get corrupted on systems where the user didn't have admin privileges has been finally fixed.“), I'll try again. Unfortunately still without success.

I have two accounts, one that I primarily work with without administrative rights and another that I can only use when I elevate something, with administrative rights.

When I perform an update for e.g. 7-Zip, it doesn't work with UniGet, it elevates it and throws a winget error that I should test “winget source reset”. If I take the same winget command that Uniget uses and run it in a PowerShell under my non-admin user, it works.  
This is the case for every package that is installed for all users / needs admin permissions.

Installations/Updates that are only for my user, i.e. installable without administrative rights, work in UniGet.

I had already deleted the Winget folder in both user directories in AppData/Local/Temp, unfortunately without success.

UniGetUI is normally installed and prompts for an elevation with my admin user at startup, which I also confirm. (No idea if this is important)

Also winget does not display any powershell 7 package updates. However, the log says it finds them, but has a problem with the manifest download. This is a second problem, I just want to also mention it here in case it is related. I do not use PowerShell 5.1, only version 7.

Any ideas?

### UniGetUI Log

<details> <summary>UniGetUI Log (click to expand)</summary><div markdown="1">

```text

[07.02.2025 10:04:40]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.6
[07.02.2025 10:04:40]
[07.02.2025 10:04:40] Build 80
[07.02.2025 10:04:40] Data directory C:\Users\<username>\AppData\Local\UniGetUI
[07.02.2025 10:04:40] Encoding Code Page set to 850
[07.02.2025 10:04:40] Using built-in UniGetUI Elevator
[07.02.2025 10:04:41] Loaded language locale: de
[07.02.2025 10:04:42] Randomly-generated background API auth token for the current session: tp4sea3wfxwkh9ttdi0rz41a6k66ah0cw4cq45erab0kyrinibmito1hglfydkdc
[07.02.2025 10:04:42] Api running on http://localhost:7058
[07.02.2025 10:04:42] Lang files were updated successfully from GitHub
[07.02.2025 10:04:43] Downloaded new icons and screenshots successfully!
[07.02.2025 10:04:43] UniGetUI Chocolatey was found in the path
[07.02.2025 10:04:43] Command cargo was not found on the system
[07.02.2025 10:04:43] Command vcpkg was not found on the system
[07.02.2025 10:04:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Program Files\WingetUI\choco-cli\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:43] Command vcpkg was not found on the system
[07.02.2025 10:04:44] Command vcpkg was not found on the system
[07.02.2025 10:04:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: vcpkg
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.25200
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.405
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\<username>\AppData\Local\Programs\Python\Python313\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.3.1 from C:\Users\<username>\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip (python 3.13)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.9.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:46] Command scoop was not found on the system
[07.02.2025 10:04:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:49] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.6
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.19041.5369                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.19041.5369                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.02.2025 10:04:50] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[07.02.2025 10:04:50] Found 1 installed packages from .NET Tool
[07.02.2025 10:04:50] Dependency .NET Tools Outdated for manager .NET Tool is present
[07.02.2025 10:04:51] Found 15 installed packages from Pip
[07.02.2025 10:04:51] Found 0 available updates from Chocolatey
[07.02.2025 10:04:52] Found 0 installed packages from Chocolatey
[07.02.2025 10:04:55] Manager WinGet failed to list available updates with exception NullReferenceException: Object reference not set to an instance of an object.
[07.02.2025 10:04:55] Since this was the first attempt, Winget.AttemptFastRepair() will be called and the procedure will be restarted
[07.02.2025 10:04:55] Attempting to reconnec to WinGet COM Server...
[07.02.2025 10:04:55] Found 0 installed packages from Npm
[07.02.2025 10:04:56] Found 105 installed packages from PowerShell7
[07.02.2025 10:04:57] Found 1 available updates from Pip
[07.02.2025 10:04:57] Found 3 installed packages from PowerShell
[07.02.2025 10:04:57] Found 0 available updates from .NET Tool
[07.02.2025 10:04:58] Found 183 installed packages from Winget
[07.02.2025 10:04:59] No Logo image found for package 9PGCV4V3BK4W in Microsoft Store response
[07.02.2025 10:04:59] Cached icon for id= is INVALID (UriSource)
[07.02.2025 10:04:59] Unknown mimetype text/html; charset=utf-8 for icon https://github.com/eizedev/PSItems/blob/master/res/logo.png, aborting download
[07.02.2025 10:05:00] Found 20 available updates from Winget
[07.02.2025 10:05:00] Found 0 available updates from Npm
[07.02.2025 10:05:01] Found 0 available updates from PowerShell
[07.02.2025 10:05:01] Cached icon for id= is INVALID (UriSource)
[07.02.2025 10:05:01] No Logo image found for package 9PK8DMSN00JJ in Microsoft Store response
[07.02.2025 10:05:02] Cached icon for id= is INVALID (UriSource)
[07.02.2025 10:05:02] Cached icon for id= is INVALID (UriSource)
[07.02.2025 10:05:02] Icon download attempt at https://github.com/devblackops/Terminal-Icons/raw/master/media/icon_256.png failed with code NotFound
[07.02.2025 10:05:04] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.PowerCLI.VCenter.Types.Appli.',Version='12.6.0.1.') with status code NotFound
[07.02.2025 10:05:04] No manifest content could be loaded for package VMware.PowerCLI.VCenter.Types.Appli. on manager PowerShell7
[07.02.2025 10:05:05] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.PowerCLI.VCenter.Types.Certi.',Version='12.6.0.1.') with status code NotFound
[07.02.2025 10:05:05] No manifest content could be loaded for package VMware.PowerCLI.VCenter.Types.Certi. on manager PowerShell7
[07.02.2025 10:05:09] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.Appliance.InfraP.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:09] No manifest content could be loaded for package VMware.Sdk.vSphere.Appliance.InfraP. on manager PowerShell7
[07.02.2025 10:05:09] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.Appliance.LocalA.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:09] No manifest content could be loaded for package VMware.Sdk.vSphere.Appliance.LocalA. on manager PowerShell7
[07.02.2025 10:05:09] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.Appliance.Networ.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:09] No manifest content could be loaded for package VMware.Sdk.vSphere.Appliance.Networ. on manager PowerShell7
[07.02.2025 10:05:09] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.Appliance.Recove.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:09] No manifest content could be loaded for package VMware.Sdk.vSphere.Appliance.Recove. on manager PowerShell7
[07.02.2025 10:05:10] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.Appliance.Suppor.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:10] No manifest content could be loaded for package VMware.Sdk.vSphere.Appliance.Suppor. on manager PowerShell7
[07.02.2025 10:05:13] Package requires elevation, forcing administrator rights...
[07.02.2025 10:05:13] Loaded operation parameters for package id=7zip.7zip on manager Winget and operation Update: update --id "7zip.7zip" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.02.2025 10:05:13] Caching admin rights for process id 14288
[07.02.2025 10:05:14] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.Authenti.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:14] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.Authenti. on manager PowerShell7
[07.02.2025 10:05:14] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.Authoriz.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:14] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.Authoriz. on manager PowerShell7
[07.02.2025 10:05:14] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.CertMana.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:14] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.CertMana. on manager PowerShell7
[07.02.2025 10:05:14] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.Consumpt.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:14] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.Consumpt. on manager PowerShell7
[07.02.2025 10:05:15] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.Deployme.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:15] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.Deployme. on manager PowerShell7
[07.02.2025 10:05:16] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.Namespac.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:16] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.Namespac. on manager PowerShell7
[07.02.2025 10:05:16] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.SystemCo.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:16] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.SystemCo. on manager PowerShell7
[07.02.2025 10:05:17] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.TrustedI.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:17] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.TrustedI. on manager PowerShell7
[07.02.2025 10:05:17] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.Sdk.vSphere.vCenter.VmTempla.',Version='8.0.1669.') with status code NotFound
[07.02.2025 10:05:17] No manifest content could be loaded for package VMware.Sdk.vSphere.vCenter.VmTempla. on manager PowerShell7
[07.02.2025 10:05:20] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='VMware.VimAutomation.WorkloadManage.',Version='12.4.0.1.') with status code NotFound
[07.02.2025 10:05:20] No manifest content could be loaded for package VMware.VimAutomation.WorkloadManage. on manager PowerShell7
[07.02.2025 10:05:55] Manager PowerShell 7.x failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager PowerShell7 did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[07.02.2025 10:05:55] Since this was the first attempt, PowerShell7.AttemptFastRepair() will be called and the procedure will be restarted
[07.02.2025 10:06:55] Error finding updates on manager PowerShell7
[07.02.2025 10:06:55] System.TimeoutException: Task _getInstalledPackages for manager PowerShell7 did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 206
```

</div></details>

### Package Managers Logs

<details> <summary>Package Manager Log (click to expand)</summary><div markdown="1">

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 07.02.2025 10:04:44
Process end time:   07.02.2025 10:04:44

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07.02.2025 10:04:50
Process end time:   07.02.2025 10:04:52

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07.02.2025 10:04:51
Process end time:   07.02.2025 10:04:58

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 07.02.2025 10:04:51
Process end time:   07.02.2025 10:04:55

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 07.02.2025 10:04:55
Process end time:   UNFINISHED

-- Task information
 ...

The task has not finished yet

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07.02.2025 10:04:55
Process end time:   07.02.2025 10:04:56

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 07.02.2025 10:04:56
Process end time:   07.02.2025 10:05:00

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 07.02.2025 10:04:56
Process end time:   07.02.2025 10:04:58

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

</div></details>

### Screenshots and videos

Screenshots from tests with 2 packages.

#### 7-Zip

Using UniGet:

![Image](https://github.com/user-attachments/assets/36285d45-2410-4fef-8e1e-08163801f17f)

Outside UniGet - running in **PowerShell 7**:

![Image](https://github.com/user-attachments/assets/87055d39-a864-4a45-8bef-711c82108e7d)

#### Adobe Acrobat

Using UniGet:

![Image](https://github.com/user-attachments/assets/eba832f7-9b2b-4aee-8003-9252a51f8bc9)

Outside Uniget - running in **CMD**:

![Image](https://github.com/user-attachments/assets/5a9df9be-8316-4230-b567-6cd34423b20b)

**Comment by rugabunda** [comment]
Same issue here 

![Image](https://github.com/user-attachments/assets/439ce878-8e23-4c53-928a-3051db9f79e1)

```
Package update operation for Package=MPC-BE.MPC-BE with Manager=Winget
Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Executing process with StartInfo:
 - FileName: "C:\Program Files\WingetUI\Assets\Utilities\UniGetUI Elevator.exe"
 - Arguments: ""c:\Users\Ty\AppData\Local\microsoft\windowsapps\winget.exe"  update --id "MPC-BE.MPC-BE" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force"
Start Time: "2/7/2025 10:33:44 AM"
Server Error: Setting token failed.
Access is denied.
Error: Failed to substitute token. Connection from server lost.
End Time: "2/7/2025 10:33:46 AM"
Process return value: "999" (0x3E7)
Operation canceled by user
```

**Comment by marticliment** [comment]
This is a different issue, please open a new bug report.

Enabling "Use GSudo instead of UniGetUI Elevator" works? (assuming you have GSudo installed on your system)

**Comment by rugabunda** [comment]
> This is a different issue, please open a new bug report.
> 
> Enabling "Use GSudo instead of UniGetUI Elevator" works? (assuming you have GSudo installed on your system)

Not sure you meant me, but I tried gsudo and it results in the same problem

**Comment by rugabunda** [comment]
> This is a different issue, please open a new bug report.
> 
> Enabling "Use GSudo instead of UniGetUI Elevator" works? (assuming you have GSudo installed on your system)


I can't create a new issue, github is blocking it.

![Image](https://github.com/user-attachments/assets/0d9a3cde-c6ad-4131-a86d-0e70df891435)

**Comment by marticliment** [comment]
Now I am able to create issues, can you try again please?

**Comment by frankgigeur** [comment]
Hello,

The same thing is happening on my side. First, it's important to understand that this is a computer lent by the company I work for, and I have an admin user and a user connected to a domain. I have access to the admin user, but I believe that this is what is causing the problem when I am using the domain account. Is there a way to disable admin elevation when we install or update software?

Btw, i unchecked Always run Winget operations with administrator rights, but nothing changes.

Thank you!

**Comment by jhermsen** [comment]
Hi,

I also have the same issue. I think it is related to UAC settings and the administrative execution of winget.
Is there also an option to skip this elevation by UniGetUI?

If I do it manually UAC kicks in to ask me for the administrative account.

**Comment by jhermsen** [comment]
Did some more testing and it is working now.
I have a different admin user account then my regular user. So with UAC I need to login as the other user.

I now logged in as the admin user also installed UniGetUI as this user for this user only.
Ran unigetUi and updated a package without any issue.
I then restarted and logged back in as regular user and UniGetUI started working under this account as well.

Not sure what it is, but might the switch of user with the elevator change the path it looks for so trying to use the admin user profile instead of the current (regular)user?

**Comment by marticliment** [comment]
Could be, I will check

**Comment by marticliment** [comment]
Does the latest 3.1.8 release work?

**Comment by jhermsen** [comment]
I did an uninstall of Uniget on my normal and admin account. 
Then rebooted and only installed on my normal account and it seems to work.
So I think it is resolved.

**Comment by code-spotting** [comment]
I'm using UniGetUI 3.2.0 and still encountered the very same issue. However, after using the steps described in [the comment above](https://github.com/marticliment/UniGetUI/issues/3274#issuecomment-2684500390), the issue is resolved and I can use the tool as intended. Thanks @jhermsen for the tip and @marticliment for the great tool!

However, you might want to consider reopening this bug.

**Comment by eizedev** [comment]
Also a final information for me. i solved it by reinstalling winget using the following method on my admin user acount:

- Log in as Admin Account and uninstall Uniget/Winget completly
- Log in as normal account
- Start PowerShell as Admin
- Reinstall winget using `Add-AppxPackage -Path "https://cdn.winget.microsoft.com/cache/source.msix"`
- Install nuget (should already exist) `Install-PackageProvider -Name NuGet -Force | Out-Null`
- Install Winget Client: `Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null`
- Running the repair function `Repair-WinGetPackageManager -Force -Latest`
- Run `winget upgrade` to check if it works

I also did a `winget source reset --force` afterwards.

Try again to upgrade installations for all users using Uniget on your normal account. After that, it is now working for me too.
