### ISSUE TITLE
[BUG] Searching in package list with key presses does not focus item

### ISSUE THREAD

**Issue by tkohlmeier** [marticliment/UniGetUI#3355]
### Please confirm these before moving forward

- [x] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [x] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [x] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [x] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.6

### Windows version, edition, and architecture

Windows 11 Pro 10.0.26100.3194

### Describe your issue

When clicking on a pakage in a package list, one can select a package by entering the name. The package is correctly selected and scrolled into view, but it does not get keyboard focus. When pressing up/down/space/enter, the previously selected item receives the event.

### Steps to reproduce the issue

- go to installed packages
- click on a package
- press a key to select another package
- press space

-> The previously clicked item gets checked instead of the one selected after pressing the key.

### UniGetUI Log

```text
not relevant
```

### Package Managers Logs

```text
not relevant
```

**Comment by mrixner** [comment]
I attempted to fix this when I originally implemented this functionality (see #3018), however I believe we determined that this is unfortunately not possible with the current UI toolkit's functionality. I would love if this would work (and as an aside, if the package list didn't reset the scroll position anytime the window loses focus), but was unable to find a way to do so.

**Comment by mrixner** [comment]
> and as an aside, if the package list didn't reset the scroll position anytime the window loses focus

Actually, I went to go open a bug report and I realized it's caused by the issue fixed by #3354

**Comment by mrixner** [comment]
Upon further investigation, I found [this StackOverflow article](https://stackoverflow.com/questions/69750255/set-focus-to-the-first-listview-item) detailing a workaround. I will see if it works when I can.

**Comment by tkohlmeier** [comment]
Yeah, I found that, too, but that is about a ListView, not an ItemsView. But I found another way to focus the package. It still does not work perfectly though.
